### ISSUE TITLE
Bug = if vote for someone and go back and set it to nothing it doesnt chnage the vote

### ISSUE THREAD

**Issue by abdulshafiq2002** [TheGrandCoding/awardsprogram#18]
Check line 584(or around) on mainform.vb for more info

**Comment by CheAle14** [comment]
If you've fixed an issue, then you can do the following in the commit message:

* `close #number` 
* `fix #number` 
* `closes #number`

[More information here](https://help.github.com/articles/closing-issues-using-keywords/)

For references sake, I think this was fixed in a318b7328 , so im closing it.
